export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RootLayout({
    children,
    users,
    revenue,
    notifications,
    ...rest
  }: {
    children: React.ReactNode,
    users:React.ReactNode,
    revenue: React.ReactNode,
    notifications: React.ReactNode
  }) {
    console.log("rest", rest);
    return (
      <div>
          {children}
          {users}
          {revenue}
          {notifications}
      </div>
    )
  }
  